import type { Publication } from '@/types';

export const publications: Publication[] = [
  {
    id: 'PMC4136787',
    title: 'Mice in Bion-M 1 space mission: training and selection',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4136787/',
    summary: 'A summary for Mice in Bion-M 1 space mission: training and selection will be generated by AI.',
    keyConcepts: [ 'Microgravity', 'Mice' ]
  },
  {
    id: 'PMC3630201',
    title: 'Microgravity induces pelvic bone loss through osteoclastic activity, osteocytic osteolysis, and osteoblastic cell cycle inhibition by CDKN1a/p21',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3630201/',
    summary: 'A summary for Microgravity induces pelvic bone loss through osteoclastic activity, osteocytic osteolysis, and osteoblastic cell cycle inhibition by CDKN1a/p21 will be generated by AI.',
    keyConcepts: [ 'Microgravity', 'Bone Loss', 'Osteoclasts' ]
  },
  {
    id: 'PMC11988870',
    title: 'Stem Cell Health and Tissue Regeneration in Microgravity',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11988870/',
    summary: 'A summary for Stem Cell Health and Tissue Regeneration in Microgravity will be generated by AI.',
    keyConcepts: [ 'Microgravity', 'Stem Cells', 'Tissue Regeneration' ]
  },
  {
    id: 'PMC7998608',
    title: 'Microgravity Reduces the Differentiation and Regenerative Potential of Embryonic Stem Cells',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7998608/',
    summary: 'A summary for Microgravity Reduces the Differentiation and Regenerative Potential of Embryonic Stem Cells will be generated by AI.',
    keyConcepts: [ 'Microgravity', 'Stem Cells' ]
  },
  {
    id: 'PMC5587110',
    title: 'Microgravity validation of a novel system for RNA isolation and multiplex quantitative real time PCR analysis of gene expression on the International Space Station',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5587110/',
    summary: 'A summary for Microgravity validation of a novel system for RNA isolation and multiplex quantitative real time PCR analysis of gene expression on the International Space Station will be generated by AI.',
    keyConcepts: [ 'Microgravity', 'Gene Expression', 'RNA Isolation' ]
  },
  {
    id: 'PMC8396460',
    title: 'Spaceflight Modulates the Expression of Key Oxidative Stress and Cell Cycle Related Genes in Heart',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8396460/',
    summary: 'A summary for Spaceflight Modulates the Expression of Key Oxidative Stress and Cell Cycle Related Genes in Heart will be generated by AI.',
    keyConcepts: [ 'Spaceflight', 'Gene Expression', 'Oxidative Stress' ]
  },
  {
    id: 'PMC5666799',
    title: 'Dose- and Ion-Dependent Effects in the Oxidative Stress Response to Space-Like Radiation Exposure in the Skeletal System',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5666799/',
    summary: 'A summary for Dose- and Ion-Dependent Effects in the Oxidative Stress Response to Space-Like Radiation Exposure in the Skeletal System will be generated by AI.',
    keyConcepts: [ 'Space Radiation', 'Oxidative Stress', 'Skeletal System' ]
  },
  {
    id: 'PMC5460236',
    title: 'From the bench to exploration medicine: NASA life sciences translational research for human exploration and habitation missions.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5460236/',
    summary: 'A summary for From the bench to exploration medicine: NASA life sciences translational research for human exploration and habitation missions. will be generated by AI.',
    keyConcepts: [ 'Translational Research', 'Human Exploration' ]
  },
  {
    id: 'PMC6222041',
    title: 'High-precision method for cyclic loading of small-animal vertebrae to assess bone quality.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6222041/',
    summary: 'A summary for High-precision method for cyclic loading of small-animal vertebrae to assess bone quality. will be generated by AI.',
    keyConcepts: [ 'Bone Quality', 'Biomechanics' ]
  },
  {
    id: 'PMC6813909',
    title: 'Effects of ex vivo ionizing radiation on collagen structure and whole-bone mechanical properties of mouse vertebrae.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6813909/',
    summary: 'A summary for Effects of ex vivo ionizing radiation on collagen structure and whole-bone mechanical properties of mouse vertebrae. will be generated by AI.',
    keyConcepts: [ 'Ionizing Radiation', 'Collagen', 'Bone Mechanics' ]
  },
  {
    id: 'PMC4095884',
    title: 'Absence of gamma-sarcoglycan alters the response of p70S6 kinase to mechanical perturbation in murine skeletal muscle',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4095884/',
    summary: 'A summary for Absence of gamma-sarcoglycan alters the response of p70S6 kinase to mechanical perturbation in murine skeletal muscle will be generated by AI.',
    keyConcepts: [ 'Skeletal Muscle', 'Mechanotransduction' ]
  },
  {
    id: 'PMC3040128',
    title: 'AtRabD2b and AtRabD2c have overlapping functions in pollen development and pollen tube growth.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3040128/',
    summary: 'A summary for AtRabD2b and AtRabD2c have overlapping functions in pollen development and pollen tube growth. will be generated by AI.',
    keyConcepts: [ 'Plant Biology', 'Pollen' ]
  },
  {
    id: 'PMC3177255',
    title: 'TNO1 is involved in salt tolerance and vacuolar trafficking in Arabidopsis.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3177255/',
    summary: 'A summary for TNO1 is involved in salt tolerance and vacuolar trafficking in Arabidopsis. will be generated by AI.',
    keyConcepts: [ 'Plant Biology', 'Salt Tolerance' ]
  },
  {
    id: 'PMC11500582',
    title: 'Functional redundancy between trans-Golgi network SNARE family members in Arabidopsis thaliana.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11500582/',
    summary: 'A summary for Functional redundancy between trans-Golgi network SNARE family members in Arabidopsis thaliana. will be generated by AI.',
    keyConcepts: [ 'Plant Biology', 'SNARE Proteins' ]
  },
  {
    id: 'PMC5387210',
    title: 'Root growth movements: Waving and skewing.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5387210/',
    summary: 'A summary for Root growth movements: Waving and skewing. will be generated by AI.',
    keyConcepts: [ 'Plant Biology', 'Root Growth' ]
  },
  {
    id: 'PMC4642138',
    title: 'Gravitropism and lateral root emergence are dependent on the trans-Golgi network protein TNO1',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4642138/',
    summary: 'A summary for Gravitropism and lateral root emergence are dependent on the trans-Golgi network protein TNO1 will be generated by AI.',
    keyConcepts: [ 'Plant Biology', 'Gravitropism' ]
  },
  {
    id: 'PMC5387210-2',
    title: 'TNO1, a TGN-localized SNARE-interacting protein, modulates root skewing in Arabidopsis thaliana.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5387210/',
    summary: 'A summary for TNO1, a TGN-localized SNARE-interacting protein, modulates root skewing in Arabidopsis thaliana. will be generated by AI.',
    keyConcepts: [ 'Plant Biology', 'Root Growth' ]
  },
  {
    id: 'PMC2915878',
    title: 'The Drosophila SUN protein Spag4 cooperates with the coiled-coil protein Yuri Gagarin to maintain association of the basal body and spermatid nucleus.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2915878/',
    summary: 'A summary for The Drosophila SUN protein Spag4 cooperates with the coiled-coil protein Yuri Gagarin to maintain association of the basal body and spermatid nucleus. will be generated by AI.',
    keyConcepts: [ 'Drosophila', 'Spermatogenesis' ]
  },
  {
    id: 'PMC3901686',
    title: 'Toll mediated infection response is altered by gravity and spaceflight in Drosophila',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3901686/',
    summary: 'A summary for Toll mediated infection response is altered by gravity and spaceflight in Drosophila will be generated by AI.',
    keyConcepts: [ 'Drosophila', 'Spaceflight', 'Immunology' ]
  },
  {
    id: 'PMC6985101',
    title: 'Multi-omics analysis of multiple missions to space reveal a theme of lipid dysregulation in mouse liver',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6985101/',
    summary: 'A summary for Multi-omics analysis of multiple missions to space reveal a theme of lipid dysregulation in mouse liver will be generated by AI.',
    keyConcepts: [ 'Spaceflight', 'Metabolomics', 'Mice' ]
  },
  {
    id: 'PMC6387434',
    title: 'GeneLab database analyses suggest long-term impact of space radiation on the cardiovascular system by the activation of FYN through reactive oxygen species.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6387434/',
    summary: 'A summary for GeneLab database analyses suggest long-term impact of space radiation on the cardiovascular system by the activation of FYN through reactive oxygen species. will be generated by AI.',
    keyConcepts: [ 'Space Radiation', 'Cardiovascular Health', 'GeneLab' ]
  },
  {
    id: 'PMC6371294',
    title: 'FAIRness and usability for open-access omics data systems.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6371294/',
    summary: 'A summary for FAIRness and usability for open-access omics data systems. will be generated by AI.',
    keyConcepts: [ 'FAIR Data', 'Omics', 'GeneLab' ]
  },
  {
    id: 'PMC7072278',
    title: 'NASA GeneLab platform utilized for biological response to space radiation in animal models',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7072278/',
    summary: 'A summary for NASA GeneLab platform utilized for biological response to space radiation in animal models will be generated by AI.',
    keyConcepts: [ 'GeneLab', 'Space Radiation', 'Animal Models' ]
  },
  {
    id: 'PMC8441986',
    title: 'Circulating miRNA spaceflight signature reveals targets for countermeasure development',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8441986/',
    summary: 'A summary for Circulating miRNA spaceflight signature reveals targets for countermeasure development will be generated by AI.',
    keyConcepts: [ 'Spaceflight', 'miRNA', 'Countermeasures' ]
  },
  {
    id: 'PMC9400218',
    title: 'Machine learning algorithm to characterize antimicrobial resistance associated with the International Space Station surface microbiome',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9400218/',
    summary: 'A summary for Machine learning algorithm to characterize antimicrobial resistance associated with the International Space Station surface microbiome will be generated by AI.',
    keyConcepts: [ 'Microbiome', 'Machine Learning', 'Antimicrobial Resistance' ]
  },
  {
    id: 'PMC9267413',
    title: 'Extraterrestrial Gynecology: Could Spaceflight Increase the Risk of Developing Cancer in Female Astronauts? An Updated Review',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9267413/',
    summary: 'A summary for Extraterrestrial Gynecology: Could Spaceflight Increase the Risk of Developing Cancer in Female Astronauts? An Updated Review will be generated by AI.',
    keyConcepts: [ 'Spaceflight', 'Cancer Risk', 'Female Health' ]
  },
  {
    id: 'PMC9576569',
    title: 'Muscle atrophy phenotype gene expression during spaceflight is linked to a metabolic crosstalk in both the liver and the muscle in mice.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9576569/',
    summary: 'A summary for Muscle atrophy phenotype gene expression during spaceflight is linked to a metabolic crosstalk in both the liver and the muscle in mice. will be generated by AI.',
    keyConcepts: [ 'Spaceflight', 'Muscle Atrophy', 'Gene Expression' ]
  },
  {
    id: 'PMC10789781',
    title: 'Chromosomal positioning and epigenetic architecture influence DNA methylation patterns triggered by galactic cosmic radiation',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10789781/',
    summary: 'A summary for Chromosomal positioning and epigenetic architecture influence DNA methylation patterns triggered by galactic cosmic radiation will be generated by AI.',
    keyConcepts: [ 'Space Radiation', 'Epigenetics', 'DNA Methylation' ]
  },
  {
    id: 'PMC10772081',
    title: 'A comprehensive SARS-CoV-2 and COVID-19 review, Part 2: Host extracellular to systemic effects of SARS-CoV-2 infection',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10772081/',
    summary: 'A summary for A comprehensive SARS-CoV-2 and COVID-19 review, Part 2: Host extracellular to systemic effects of SARS-CoV-2 infection will be generated by AI.',
    keyConcepts: [ 'COVID-19', 'SARS-CoV-2' ]
  },
  {
    id: 'PMC11166946',
    title: 'Aging and putative frailty biomarkers are altered by spaceflight',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11166946/',
    summary: 'A summary for Aging and putative frailty biomarkers are altered by spaceflight will be generated by AI.',
    keyConcepts: [ 'Spaceflight', 'Aging', 'Biomarkers' ]
  },
  {
    id: 'PMC11166944',
    title: 'Space radiation damage rescued by inhibition of key spaceflight associated miRNAs',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11166944/',
    summary: 'A summary for Space radiation damage rescued by inhibition of key spaceflight associated miRNAs will be generated by AI.',
    keyConcepts: [ 'Space Radiation', 'miRNA', 'DNA Repair' ]
  },
  {
    id: 'PMC11166968',
    title: 'Ethical considerations for the age of non-governmental space exploration',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11166968/',
    summary: 'A summary for Ethical considerations for the age of non-governmental space exploration will be generated by AI.',
    keyConcepts: [ 'Space Exploration', 'Ethics' ]
  },
  {
    id: 'PMC7000411',
    title: 'Innate immune responses of Drosophila melanogaster are altered by spaceflight.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7000411/',
    summary: 'A summary for Innate immune responses of Drosophila melanogaster are altered by spaceflight. will be generated by AI.',
    keyConcepts: [ 'Drosophila', 'Spaceflight', 'Immunology' ]
  },
  {
    id: 'PMC7787258',
    title: 'Prolonged Exposure to Microgravity Reduces Cardiac Contractility and Initiates Remodeling in Drosophila',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7787258/',
    summary: 'A summary for Prolonged Exposure to Microgravity Reduces Cardiac Contractility and Initiates Remodeling in Drosophila will be generated by AI.',
    keyConcepts: [ 'Drosophila', 'Microgravity', 'Cardiovascular Health' ]
  },
  {
    id: 'PMC8716943',
    title: 'Regulation of plant gravity sensing and signaling by the actin cytoskeleton.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8716943/',
    summary: 'A summary for Regulation of plant gravity sensing and signaling by the actin cytoskeleton. will be generated by AI.',
    keyConcepts: [ 'Plant Biology', 'Gravitropism', 'Actin' ]
  },
  {
    id: 'PMC4826010',
    title: 'HLB1 Is a Tetratricopeptide Repeat Domain-Containing Protein That Operates at the Intersection of the Exocytic and Endocytic Pathways at the TGN/EE in Arabidopsis',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4826010/',
    summary: 'A summary for HLB1 Is a Tetratricopeptide Repeat Domain-Containing Protein That Operates at the Intersection of the Exocytic and Endocytic Pathways at the TGN/EE in Arabidopsis will be generated by AI.',
    keyConcepts: [ 'Plant Biology', 'Cell Biology' ]
  },
  {
    id: 'PMC6048781',
    title: 'ERULUS is a plasma membrane-localized receptor-like kinase that specifies root hair growth by maintaining tip-focused cytoplasmic calcium oscillations.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6048781/',
    summary: 'A summary for ERULUS is a plasma membrane-localized receptor-like kinase that specifies root hair growth by maintaining tip-focused cytoplasmic calcium oscillations. will be generated by AI.',
    keyConcepts: [ 'Plant Biology', 'Root Growth', 'Calcium Signaling' ]
  },
  {
    id: 'PMC7010715',
    title: 'Brassinosteroids inhibit autotropic root straightening by modifying filamentous-actin organization and dynamics.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7010715/',
    summary: 'A summary for Brassinosteroids inhibit autotropic root straightening by modifying filamentous-actin organization and dynamics. will be generated by AI.',
    keyConcepts: [ 'Plant Biology', 'Root Growth', 'Hormones' ]
  },
  {
    id: 'PMC7503278',
    title: 'Cell type-specific imaging of calcium signaling in Arabidopsis thaliana seedling roots using GCaMP3.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7503278/',
    summary: 'A summary for Cell type-specific imaging of calcium signaling in Arabidopsis thaliana seedling roots using GCaMP3. will be generated by AI.',
    keyConcepts: [ 'Plant Biology', 'Calcium Signaling', 'Imaging' ]
  },
  {
    id: 'PMC8364238',
    title: 'Spatial and temporal localization of SPIRRIG and WAVE/SCAR reveal roles for these proteins in actin-mediated root hair development.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8364238/',
    summary: 'A summary for Spatial and temporal localization of SPIRRIG and WAVE/SCAR reveal roles for these proteins in actin-mediated root hair development. will be generated by AI.',
    keyConcepts: [ 'Plant Biology', 'Root Growth', 'Actin' ]
  },
  {
    id: 'PMC11579474',
    title: 'Microgravity Stress: Bone and Connective Tissue',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11579474/',
    summary: 'A summary for Microgravity Stress: Bone and Connective Tissue will be generated by AI.',
    keyConcepts: [ 'Microgravity', 'Bone Loss', 'Connective Tissue' ]
  },
  {
    id: 'PMC2998437',
    title: 'S. aureus MscL is a pentamer in vivo but of variable stoichiometries in vitro: implications for detergent-solubilized membrane proteins',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2998437/',
    summary: 'A summary for S. aureus MscL is a pentamer in vivo but of variable stoichiometries in vitro: implications for detergent-solubilized membrane proteins will be generated by AI.',
    keyConcepts: [ 'Mechanosensitive Channels', 'Membrane Proteins' ]
  },
  {
    id: 'PMC3005423',
    title: 'Manipulating the permeation of charged compounds through the MscL nanovalve.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3005423/',
    summary: 'A summary for Manipulating the permeation of charged compounds through the MscL nanovalve. will be generated by AI.',
    keyConcepts: [ 'Mechanosensitive Channels', 'Nanotechnology' ]
  },
  {
    id: 'PMC3190158',
    title: 'The oligomeric state of the truncated mechanosensitive channel of large conductance shows no variance in vivo.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3190158/',
    summary: 'A summary for The oligomeric state of the truncated mechanosensitive channel of large conductance shows no variance in vivo. will be generated by AI.',
    keyConcepts: [ 'Mechanosensitive Channels', 'Membrane Proteins' ]
  },
  {
    id: 'PMC3289768',
    title: 'Three routes to modulate the pore size of the MscL channel/nanovalve',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3289768/',
    summary: 'A summary for Three routes to modulate the pore size of the MscL channel/nanovalve will be generated by AI.',
    keyConcepts: [ 'Mechanosensitive Channels', 'Nanotechnology' ]
  },
  {
    id: 'PMC3508904',
    title: 'The dynamics of protein-protein interactions between domains of MscL at the cytoplasmic-lipid interface',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3508904/',
    summary: 'A summary for The dynamics of protein-protein interactions between domains of MscL at the cytoplasmic-lipid interface will be generated by AI.',
    keyConcepts: [ 'Mechanosensitive Channels', 'Protein Interactions' ]
  },
  {
    id: 'PMC3430326',
    title: 'The MscS and MscL families of mechanosensitive channels act as microbial emergency release valves',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3430326/',
    summary: 'A summary for The MscS and MscL families of mechanosensitive channels act as microbial emergency release valves will be generated by AI.',
    keyConcepts: [ 'Mechanosensitive Channels', 'Microbiology' ]
  },
  {
    id: 'PMC3593973',
    title: 'Chimeras reveal a single lipid-interface residue that controls MscL channel kinetics as well as mechanosensitivity',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3593973/',
    summary: 'A summary for Chimeras reveal a single lipid-interface residue that controls MscL channel kinetics as well as mechanosensitivity will be generated by AI.',
    keyConcepts: [ 'Mechanosensitive Channels', 'Protein Engineering' ]
  },
  {
    id: 'PMC5018776',
    title: 'Evidence for extensive horizontal gene transfer from the draft genome of a tardigrade',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5018776/',
    summary: 'A summary for Evidence for extensive horizontal gene transfer from the draft genome of a tardigrade will be generated by AI.',
    keyConcepts: [ 'Tardigrades', 'Genomics', 'Horizontal Gene Transfer' ]
  },
  {
    id: 'PMC4896697',
    title: 'Reply to Bemm et al. and Arakawa: Identifying foreign genes in independent Hypsibius dujardini genome assemblies',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4896697/',
    summary: 'A summary for Reply to Bemm et al. and Arakawa: Identifying foreign genes in independent Hypsibius dujardini genome assemblies will be generated by AI.',
    keyConcepts: [ 'Tardigrades', 'Genomics', 'Horizontal Gene Transfer' ]
  },
  {
    id: 'PMC11127935',
    title: 'Tardigrades Use Intrinsically Disordered Proteins to Survive Desiccation.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11127935/',
    summary: 'A summary for Tardigrades Use Intrinsically Disordered Proteins to Survive Desiccation. will be generated by AI.',
    keyConcepts: [ 'Tardigrades', 'Anhydrobiosis', 'IDPs' ]
  },
  {
    id: 'PMC11831363',
    title: 'Desiccation of Hypsibius exemplaris',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11831363/',
    summary: 'A summary for Desiccation of Hypsibius exemplaris will be generated by AI.',
    keyConcepts: [ 'Tardigrades', 'Anhydrobiosis' ]
  },
  {
    id: 'PMC11930778',
    title: 'The biology of tardigrade disordered proteins in extreme stress tolerance.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11930778/',
    summary: 'A summary for The biology of tardigrade disordered proteins in extreme stress tolerance. will be generated by AI.',
    keyConcepts: [ 'Tardigrades', 'Anhydrobiosis', 'IDPs' ]
  },
  {
    id: 'PMC8816950',
    title: 'Production of reactive oxygen species and involvement of bioprotectants during anhydrobiosis in the tardigrade Paramacrobiotus spatialis',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8816950/',
    summary: 'A summary for Production of reactive oxygen species and involvement of bioprotectants during anhydrobiosis in the tardigrade Paramacrobiotus spatialis will be generated by AI.',
    keyConcepts: [ 'Tardigrades', 'Anhydrobiosis', 'Oxidative Stress' ]
  },
  {
    id: 'PMC3774184',
    title: 'Partial weight suspension: A novel murine model for investigating adaptation to reduced musculoskeletal loading.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3774184/',
    summary: 'A summary for Partial weight suspension: A novel murine model for investigating adaptation to reduced musculoskeletal loading. will be generated by AI.',
    keyConcepts: [ 'Hindlimb Unloading', 'Microgravity Simulation', 'Animal Models' ]
  },
  {
    id: 'PMC4118556',
    title: 'Partial reductions in mechanical loading yield proportional changes in bone density, bone architecture, and muscle mass',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4118556/',
    summary: 'A summary for Partial reductions in mechanical loading yield proportional changes in bone density, bone architecture, and muscle mass will be generated by AI.',
    keyConcepts: [ 'Hindlimb Unloading', 'Bone Loss', 'Muscle Atrophy' ]
  },
  {
    id: 'PMC4653813',
    title: 'Spaceflight and hind limb unloading induce similar changes in electrical impedance characteristics of mouse gastrocnemius muscle',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4653813/',
    summary: 'A summary for Spaceflight and hind limb unloading induce similar changes in electrical impedance characteristics of mouse gastrocnemius muscle will be generated by AI.',
    keyConcepts: [ 'Spaceflight', 'Hindlimb Unloading', 'Muscle Atrophy' ]
  },
  {
    id: 'PMC6915713',
    title: 'Spaceflight Activates Lipotoxic Pathways in Mouse Liver',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6915713/',
    summary: 'A summary for Spaceflight Activates Lipotoxic Pathways in Mouse Liver will be generated by AI.',
    keyConcepts: [ 'Spaceflight', 'Metabolomics', 'Mice' ]
  },
  {
    id: 'PMC6124165',
    title: 'Treatment with a soluble bone morphogenetic protein type 1A receptor (BMPR1A) fusion protein increases bone mass and bone formation in mice subjected to hindlimb unloading.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6124165/',
    summary: 'A summary for Treatment with a soluble bone morphogenetic protein type 1A receptor (BMPR1A) fusion protein increases bone mass and bone formation in mice subjected to hindlimb unloading. will be generated by AI.',
    keyConcepts: [ 'Hindlimb Unloading', 'Bone Loss', 'Countermeasures' ]
  },
  {
    id: 'PMC8509868',
    title: 'RNAseq and RNA molecular barcoding reveal differential gene expression in cortical bone following hindlimb unloading in female mice',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8509868/',
    summary: 'A summary for RNAseq and RNA molecular barcoding reveal differential gene expression in cortical bone following hindlimb unloading in female mice will be generated by AI.',
    keyConcepts: [ 'Hindlimb Unloading', 'Gene Expression', 'Bone Loss' ]
  },
  {
    id: 'PMC11063234',
    title: 'Proteomic and phosphoproteomic characterization of cardiovascular tissues after long term exposure to simulated space radiation',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11063234/',
    summary: 'A summary for Proteomic and phosphoproteomic characterization of cardiovascular tissues after long term exposure to simulated space radiation will be generated by AI.',
    keyConcepts: [ 'Space Radiation', 'Cardiovascular Health', 'Proteomics' ]
  },
  {
    id: 'PMC5672023',
    title: 'Adaptive Changes in the Vestibular System of Land Snail to a 30-Day Spaceflight and Readaptation on Return to Earth',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5672023/',
    summary: 'A summary for Adaptive Changes in the Vestibular System of Land Snail to a 30-Day Spaceflight and Readaptation on Return to Earth will be generated by AI.',
    keyConcepts: [ 'Spaceflight', 'Vestibular System', 'Neuroscience' ]
  },
  {
    id: 'PMC5899691',
    title: 'Morphology of the Utricular Otolith Organ in the Toadfish, Opsanus tau',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5899691/',
    summary: 'A summary for Morphology of the Utricular Otolith Organ in the Toadfish, Opsanus tau will be generated by AI.',
    keyConcepts: [ 'Vestibular System', 'Neuroscience' ]
  },
  {
    id: 'PMC6204554',
    title: 'Influence of Magnitude and Duration of Altered Gravity and Readaptation to 1g on the Structure and Function of the Utricle in Toadfish, Opsanus tau.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6204554/',
    summary: 'A summary for Influence of Magnitude and Duration of Altered Gravity and Readaptation to 1g on the Structure and Function of the Utricle in Toadfish, Opsanus tau. will be generated by AI.',
    keyConcepts: [ 'Vestibular System', 'Neuroscience', 'Hypergravity' ]
  },
  {
    id: 'PMC4064004',
    title: 'Organization of the ER-Golgi interface for membrane traffic control.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4064004/',
    summary: 'A summary for Organization of the ER-Golgi interface for membrane traffic control. will be generated by AI.',
    keyConcepts: [ 'Cell Biology', 'ER', 'Golgi' ]
  },
  {
    id: 'PMC3818365',
    title: 'IRE1: ER stress sensor and cell fate executor.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3818365/',
    summary: 'A summary for IRE1: ER stress sensor and cell fate executor. will be generated by AI.',
    keyConcepts: [ 'Cell Biology', 'ER Stress', 'UPR' ]
  },
  {
    id: 'PMC3981873',
    title: 'Inter-regulation of the unfolded protein response and auxin signaling.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3981873/',
    summary: 'A summary for Inter-regulation of the unfolded protein response and auxin signaling. will be generated by AI.',
    keyConcepts: [ 'Plant Biology', 'ER Stress', 'UPR' ]
  },
  {
    id: 'PMC4150462',
    title: 'Endoplasmic reticulum-shape and function in stress translation',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4150462/',
    summary: 'A summary for Endoplasmic reticulum-shape and function in stress translation will be generated by AI.',
    keyConcepts: [ 'Cell Biology', 'ER Stress' ]
  },
  {
    id: 'PMC4378170',
    title: 'Galactose-depleted xycoglucan is dysfunctional and leads to dwarfism in Arabidopsis',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4378170/',
    summary: 'A summary for Galactose-depleted xycoglucan is dysfunctional and leads to dwarfism in Arabidopsis will be generated by AI.',
    keyConcepts: [ 'Plant Biology', 'Cell Wall' ]
  },
  {
    id: 'PMC4618186',
    title: 'Unfolded protein response in plants: one master, many questions.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4618186/',
    summary: 'A summary for Unfolded protein response in plants: one master, many questions. will be generated by AI.',
    keyConcepts: [ 'Plant Biology', 'ER Stress', 'UPR' ]
  },
  {
    id: 'PMC4453782',
    title: 'Vesicles versus Tubes: Is Endoplasmic Reticulum-Golgi Transport in Plants Fundamentally Different from Other Eukaryotes?',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4453782/',
    summary: 'A summary for Vesicles versus Tubes: Is Endoplasmic Reticulum-Golgi Transport in Plants Fundamentally Different from Other Eukaryotes? will be generated by AI.',
    keyConcepts: [ 'Plant Biology', 'Cell Biology', 'ER', 'Golgi' ]
  },
  {
    id: 'PMC4902601',
    title: 'Pectin methylesterification impacts the relationship between photosynthesis and plant growth.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4902601/',
    summary: 'A summary for Pectin methylesterification impacts the relationship between photosynthesis and plant growth. will be generated by AI.',
    keyConcepts: [ 'Plant Biology', 'Cell Wall', 'Photosynthesis' ]
  },
  {
    id: 'PMC4776492',
    title: 'Reduced Chloroplast Coverage genes from Arabidopsis thaliana help to establish the size of the chloroplast compartment',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4776492/',
    summary: 'A summary for Reduced Chloroplast Coverage genes from Arabidopsis thaliana help to establish the size of the chloroplast compartment will be generated by AI.',
    keyConcepts: [ 'Plant Biology', 'Chloroplasts' ]
  },
  {
    id: 'PMC5415411',
    title: 'Maintaining the factory: The roles of the unfolded protein response in cellular homeostasis in plants.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5415411/',
    summary: 'A summary for Maintaining the factory: The roles of the unfolded protein response in cellular homeostasis in plants. will be generated by AI.',
    keyConcepts: [ 'Plant Biology', 'ER Stress', 'UPR' ]
  },
  {
    id: 'PMC6289879',
    title: 'NADPH oxidase activity is required for ER stress survival in plants.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6289879/',
    summary: 'A summary for NADPH oxidase activity is required for ER stress survival in plants. will be generated by AI.',
    keyConcepts: [ 'Plant Biology', 'ER Stress', 'Oxidative Stress' ]
  },
  {
    id: 'PMC7987364',
    title: 'Relevance of the Unfolded Protein Response to Spaceflight-Induced Transcriptional Reprogramming in Arabidopsis',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7987364/',
    summary: 'A summary for Relevance of the Unfolded Protein Response to Spaceflight-Induced Transcriptional Reprogramming in Arabidopsis will be generated by AI.',
    keyConcepts: [ 'Spaceflight', 'Plant Biology', 'UPR' ]
  },
  {
    id: 'PMC8099722',
    title: 'Reanalysis of the Mars500 experiment reveals common gut microbiome alterations in astronauts induced by long-duration confinement',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8099722/',
    summary: 'A summary for Reanalysis of the Mars500 experiment reveals common gut microbiome alterations in astronauts induced by long-duration confinement will be generated by AI.',
    keyConcepts: [ 'Microbiome', 'Human Physiology', 'Confinement' ]
  },
  {
    id: 'PMC5116466',
    title: 'High atomic weight, high-energy radiation (HZE) induces transcriptional responses shared with conventional stresses in addition to a core "DSB" response specific to clastogenic treatments',
    link: 'https://www.ncbi.nlm_nih_gov/pmc/articles/PMC5116466/',
    summary: 'A summary for High atomic weight, high-energy radiation (HZE) induces transcriptional responses shared with conventional stresses in addition to a core "DSB" response specific to clastogenic treatments will be generated by AI.',
    keyConcepts: [ 'Space Radiation', 'Gene Expression', 'DNA Repair' ]
  },
  {
    id: 'PMC4033213',
    title: 'Genomic stability in response to high versus low linear energy transfer radiation in Arabidopsis thaliana',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4033213/',
    summary: 'A summary for Genomic stability in response to high versus low linear energy transfer radiation in Arabidopsis thaliana will be generated by AI.',
    keyConcepts: [ 'Space Radiation', 'Plant Biology', 'Genomics' ]
  },
  {
    id: 'PMC6081456',
    title: 'Acceleration profiles and processing methods for parabolic flight.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6081456/',
    summary: 'A summary for Acceleration profiles and processing methods for parabolic flight. will be generated by AI.',
    keyConcepts: [ 'Parabolic Flight', 'Microgravity Simulation' ]
  },
  {
    id: 'PMC5955502',
    title: 'Cytoskeleton structure and total methylation of mouse cardiac and lung tissue during space flight.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5955502/',
    summary: 'A summary for Cytoskeleton structure and total methylation of mouse cardiac and lung tissue during space flight. will be generated by AI.',
    keyConcepts: [ 'Spaceflight', 'Cytoskeleton', 'Epigenetics' ]
  },
  {
    id: 'PMC10285634',
    title: 'Toward countering muscle and bone loss with spaceflight: GSK3 as a potential target',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10285634/',
    summary: 'A summary for Toward countering muscle and bone loss with spaceflight: GSK3 as a potential target will be generated by AI.',
    keyConcepts: [ 'Spaceflight', 'Muscle Atrophy', 'Bone Loss', 'Countermeasures' ]
  },
  {
    id: 'PMC11271499',
    title: 'Spaceflight increases sarcoplasmic reticulum Ca2+ leak and this cannot be counteracted with BuOE treatment',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11271499/',
    summary: 'A summary for Spaceflight increases sarcoplasmic reticulum Ca2+ leak and this cannot be counteracted with BuOE treatment will be generated by AI.',
    keyConcepts: [ 'Spaceflight', 'Muscle Atrophy', 'Calcium Signaling' ]
  },
  {
    id: 'PMC6062551',
    title: 'Cardiovascular progenitor cells cultured aboard the International Space Station exhibit altered developmental and functional properties',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6062551/',
    summary: 'A summary for Cardiovascular progenitor cells cultured aboard the International Space Station exhibit altered developmental and functional properties will be generated by AI.',
    keyConcepts: [ 'Spaceflight', 'Stem Cells', 'Cardiovascular Health' ]
  },
  {
    id: 'PMC9832585',
    title: 'Inter-agency perspective: Translating advances in biomarker discovery and medical countermeasures development between terrestrial and space radiation environments',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9832585/',
    summary: 'A summary for Inter-agency perspective: Translating advances in biomarker discovery and medical countermeasures development between terrestrial and space radiation environments will be generated by AI.',
    keyConcepts: [ 'Space Radiation', 'Countermeasures', 'Biomarkers' ]
  },
  {
    id: 'PMC7829349',
    title: 'Genomic and functional characterization of Enterococcus faecalis isolates recovered from the International Space Station and their potential for pathogenicity',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7829349/',
    summary: 'A summary for Genomic and functional characterization of Enterococcus faecalis isolates recovered from the International Space Station and their potential for pathogenicity will be generated by AI.',
    keyConcepts: [ 'Microbiome', 'ISS', 'Pathogens' ]
  },
  {
    id: 'PMC3570223',
    title: 'Evaluation of in vitro macrophage differentiation during space flight.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3570223/',
    summary: 'A summary for Evaluation of in vitro macrophage differentiation during space flight. will be generated by AI.',
    keyConcepts: [ 'Spaceflight', 'Immunology', 'Macrophages' ]
  },
  {
    id: 'PMC3457586',
    title: 'Identification of critical host mitochondrion-associated genes during Ehrlichia chaffeensis infections',
    link: 'https://www_ncbi_nlm_nih_gov/pmc/articles/PMC3457586/',
    summary: 'A summary for Identification of critical host mitochondrion-associated genes during Ehrlichia chaffeensis infections will be generated by AI.',
    keyConcepts: [ 'Immunology', 'Mitochondria' ]
  },
  {
    id: 'PMC3558598',
    title: 'Ehrlichia chaffeensis replication sites in adult Drosophila melanogaster.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3558598/',
    summary: 'A summary for Ehrlichia chaffeensis replication sites in adult Drosophila melanogaster. will be generated by AI.',
    keyConcepts: [ 'Immunology', 'Drosophila' ]
  },
  {
    id: 'PMC11046949',
    title: 'Development and characterization of two porcine monocyte-derived macrophage cell lines.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11046949/',
    summary: 'A summary for Development and characterization of two porcine monocyte-derived macrophage cell lines. will be generated by AI.',
    keyConcepts: [ 'Immunology', 'Macrophages' ]
  },
  {
    id: 'PMC3890248',
    title: 'Understanding macrophage differentiation during space flight: The importance of ground-based experiments before space flight',
    link: 'https://www_ncbi_nlm_nih_gov/pmc/articles/PMC3890248/',
    summary: 'A summary for Understanding macrophage differentiation during space flight: The importance of ground-based experiments before space flight will be generated by AI.',
    keyConcepts: [ 'Spaceflight', 'Immunology', 'Macrophages' ]
  },
  {
    id: 'PMC3868799',
    title: 'Bone marrow leptin signaling mediates obesity-associated adipose tissue inflammation in male mice.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3868799/',
    summary: 'A summary for Bone marrow leptin signaling mediates obesity-associated adipose tissue inflammation in male mice. will be generated by AI.',
    keyConcepts: [ 'Immunology', 'Metabolism' ]
  },
  {
    id: 'PMC4960141',
    title: 'Establishment and characterization of DB-1: a leptin receptor-deficient murine macrophage cell line',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4960141/',
    summary: 'A summary for Establishment and characterization of DB-1: a leptin receptor-deficient murine macrophage cell line will be generated by AI.',
    keyConcepts: [ 'Immunology', 'Macrophages' ]
  },
  {
    id: 'PMC5736159',
    title: 'Validation of methods to assess the immunoglobulin gene repertoire in tissues obtained from mice on the International Space Station.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5736159/',
    summary: 'A summary for Validation of methods to assess the immunoglobulin gene repertoire in tissues obtained from mice on the International Space Station. will be generated by AI.',
    keyConcepts: [ 'Spaceflight', 'Immunology', 'Genomics' ]
  },
  {
    id: 'PMC5761896',
    title: 'Characterization of the naive murine antibody repertoire using unamplified high-throughput sequencing',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5761896/',
    summary: 'A summary for Characterization of the naive murine antibody repertoire using unamplified high-throughput sequencing will be generated by AI.',
    keyConcepts: [ 'Immunology', 'Genomics' ]
  },
  {
    id: 'PMC5826609',
    title: 'Effects of spaceflight on the immunoglobulin repertoire of unimmunized C57BL/6 mice',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5826609/',
    summary: 'A summary for Effects of spaceflight on the immunoglobulin repertoire of unimmunized C57BL/6 mice will be generated by AI.',
    keyConcepts: [ 'Spaceflight', 'Immunology', 'Genomics' ]
  },
  {
    id: 'PMC6366624',
    title: 'A comparison of unamplified and massively multiplexed PCR amplification for murine antibody repertoire sequencing.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6366624/',
    summary: 'A summary for A comparison of unamplified and massively multiplexed PCR amplification for murine antibody repertoire sequencing. will be generated by AI.',
    keyConcepts: [ 'Immunology', 'Genomics' ]
  },
  {
    id: 'PMC11929063',
    title: 'Effects of skeletal unloading on the antibody repertoire of tetanus toxoid and/or CpG treated C57BL/6J mice.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11929063/',
    summary: 'A summary for Effects of skeletal unloading on the antibody repertoire of tetanus toxoid and/or CpG treated C57BL/6J mice. will be generated by AI.',
    keyConcepts: [ 'Hindlimb Unloading', 'Immunology', 'Genomics' ]
  },
  {
    id: 'PMC11929063-2',
    title: 'Effects of skeletal unloading on the bone marrow antibody repertoire of tetanus toxoid and/or CpG treated C57BL/6J mice.',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11929063/',
    summary: 'A summary for Effects of skeletal unloading on the bone marrow antibody repertoire of tetanus toxoid and/or CpG treated C57BL/6J mice. will be generated by AI.',
    keyConcepts: [ 'Hindlimb Unloading', 'Immunology', 'Genomics' ]
  },
  {
    id: 'PMC10996920',
    title: 'An Analysis of the Effects of Spaceflight and Vaccination on Antibody Repertoire Diversity',
    link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10996920/',
    summary: 'A summary for An Analysis of the Effects of Spaceflight and Vaccination on Antibody Repertoire Diversity will be generated by AI.',
    keyConcepts: [ 'Spaceflight', 'Immunology', 'Genomics' ]
  }
];
