import type { Publication } from '@/types';

export const publications: Publication[] = [
  {
    id: 'nasa-bio-001',
    title: 'Microgravity-Induced Alterations in Plant Cell Wall Composition',
    authors: ['Dr. Evelyn Reed', 'Dr. Samuel Chen'],
    publicationDate: '2023-05-12',
    journal: 'Astrobiology Journal',
    summary: 'This study investigates the structural changes in the cell walls of Arabidopsis thaliana grown under simulated microgravity. We observed significant reductions in lignin content and alterations in pectin distribution, suggesting adaptive responses to mechanical unloading.',
    keyConcepts: ['Microgravity', 'Plant Biology', 'Cell Wall', 'Lignin', 'Pectin'],
    fullText: 'Full text content detailing the experimental setup, methodology, results, and discussion on plant cell wall adaptation in space...',
    doi: '10.1089/ast.2023.0123',
  },
  {
    id: 'nasa-bio-002',
    title: 'Human Immune Response to Long-Duration Spaceflight',
    authors: ['Dr. Maria Santos', 'Dr. Ben Carter'],
    publicationDate: '2022-11-20',
    journal: 'Journal of Applied Physiology',
    summary: 'Analysis of astronaut blood samples reveals a consistent dysregulation of T-cell activation and cytokine production during missions exceeding six months. These findings highlight the need for immunological countermeasures for future Mars missions.',
    keyConcepts: ['Immunology', 'Spaceflight', 'T-cells', 'Cytokines', 'Human Physiology'],
    fullText: 'In-depth analysis of immune markers, including flow cytometry data and transcriptomic profiling of peripheral blood mononuclear cells...',
    doi: '10.1152/japplphysiol.00123.2022',
  },
  {
    id: 'nasa-bio-003',
    title: 'CRISPR-Cas9 for In-Situ DNA Repair in Space Radiation Environments',
    authors: ['Dr. Kenji Tanaka', 'Dr. Lena Petrova'],
    publicationDate: '2024-01-30',
    journal: 'Nature Biotechnology',
    summary: 'We demonstrate a novel application of CRISPR-Cas9 technology to correct DNA double-strand breaks induced by galactic cosmic radiation (GCR) in human cell lines. The system shows high fidelity and efficiency, paving the way for on-demand gene therapy during space missions.',
    keyConcepts: ['CRISPR', 'DNA Repair', 'Space Radiation', 'Gene Therapy', 'GCR'],
    fullText: 'Detailed methodology on the guide RNA design, delivery mechanisms via adenoviral vectors, and quantification of off-target effects...',
    doi: '10.1038/s41587-024-01234-5',
  },
  {
    id: 'nasa-bio-004',
    title: 'Metabolic Profiling of Extremophiles from Martian Analogue Environments',
    authors: ['Dr. Aisha Khan', 'Dr. Omar Bakri'],
    publicationDate: '2023-08-01',
    journal: 'Geobiology',
    summary: 'Metabolomic analysis of bacteria isolated from the Atacama Desert reveals unique metabolic pathways for survival in extreme desiccation and high-UV conditions. These pathways provide a blueprint for searching for life on Mars.',
    keyConcepts: ['Extremophiles', 'Metabolomics', 'Mars Analogue', 'Astrobiology', 'Life Detection'],
    fullText: 'Comprehensive data from mass spectrometry and NMR spectroscopy, identifying novel osmoprotectants and UV-screening compounds...',
    doi: '10.1111/gbi.12456',
  },
  {
    id: 'nasa-bio-005',
    title: 'The Gut Microbiome and its Role in Astronaut Health',
    authors: ['Dr. David Kim', 'Dr. Rachel Green'],
    publicationDate: '2022-09-15',
    journal: 'Cell Host & Microbe',
    summary: 'A longitudinal study of the astronaut gut microbiome shows a significant shift in microbial diversity and function during spaceflight, correlated with increased inflammatory markers. Probiotic interventions are discussed as a potential countermeasure.',
    keyConcepts: ['Microbiome', 'Spaceflight', 'Human Physiology', 'Inflammation', 'Probiotics'],
    fullText: '16S rRNA sequencing data and shotgun metagenomics results from multiple astronauts over the course of their missions on the ISS...',
    doi: '10.1016/j.chom.2022.08.001',
  },
  {
    id: 'nasa-bio-006',
    title: 'Bone Density Loss in Microgravity: A Multi-Scale Mechanobiological Model',
    authors: ['Dr. Frank Miller', 'Dr. Chloe Bianchi'],
    publicationDate: '2023-03-22',
    journal: 'Bone',
    summary: 'We developed a computational model that integrates cellular signaling with tissue-level mechanics to predict bone density loss in astronauts. The model accurately simulates the effects of exercise countermeasures and identifies osteocyte mechanosensitivity as a key factor.',
    keyConcepts: ['Bone Loss', 'Microgravity', 'Computational Model', 'Mechanobiology', 'Human Physiology'],
    fullText: 'Detailed description of the finite element model, the underlying mathematical equations governing cell behavior, and validation against astronaut data...',
    doi: '10.1016/j.bone.2023.116543',
  },
  {
    id: 'nasa-bio-007',
    title: 'Algae-Based Life Support Systems for Oxygen and Biomass Production',
    authors: ['Dr. Hannah Weiss', 'Dr. Leo Martinez'],
    publicationDate: '2024-02-11',
    journal: 'Life Sciences in Space Research',
    summary: 'This paper details the optimization of a photobioreactor using Chlamydomonas reinhardtii for a closed-loop life support system. The system achieved a 95% oxygen regeneration rate and produced edible, protein-rich biomass.',
    keyConcepts: ['Life Support', 'Algae', 'Oxygen Production', 'Biomass', 'Photobioreactor'],
    fullText: 'Engineering schematics of the bioreactor, data on gas exchange rates, nutrient cycling, and biochemical analysis of the generated biomass...',
    doi: '10.1016/j.lssr.2024.01.002',
  },
  {
    id: 'nasa-bio-008',
    title: 'Cognitive Performance and Brain Plasticity During Spaceflight',
    authors: ['Dr. Ivan Volkov', 'Dr. Susan Taylor'],
    publicationDate: '2023-10-05',
    journal: 'NeuroImage',
    summary: 'Using fMRI data, we observed significant neuroplastic changes in astronauts\' sensorimotor cortex, a phenomenon termed "Space Brain." While some cognitive functions were impaired, others, like spatial reasoning, showed enhancement.',
    keyConcepts: ['Neuroscience', 'Cognitive Science', 'fMRI', 'Spaceflight', 'Neuroplasticity'],
    fullText: 'Longitudinal fMRI and cognitive testing data from before, during, and after spaceflight missions, with advanced connectivity analysis...',
    doi: '10.1016/j.neuroimage.2023.120123',
  },
  {
    id: 'nasa-bio-009',
    title: 'Survival of Tardigrades Under Simulated Hypervelocity Impacts',
    authors: ['Dr. Isabella Rossi'],
    publicationDate: '2022-07-19',
    journal: 'Icarus',
    summary: 'Tardigrades (water bears) were subjected to hypervelocity impacts mimicking meteorite transfers between planetary bodies. A surprising percentage survived impacts up to 0.9 km/s, supporting the hypothesis of panspermia.',
    keyConcepts: ['Panspermia', 'Tardigrades', 'Extremophiles', 'Astrobiology', 'Hypervelocity Impact'],
    fullText: 'Experimental setup using a two-stage light-gas gun, analysis of tardigrade survival and subsequent reproduction rates...',
    doi: '10.1016/j.icarus.2022.115001',
  },
  {
    id: 'nasa-bio-010',
    title: 'Synthetic Biology for On-Demand Pharmaceutical Production on Mars',
    authors: ['Dr. Anika Sharma', 'Dr. Raj Patel'],
    publicationDate: '2024-03-01',
    journal: 'ACS Synthetic Biology',
    summary: 'We engineered yeast to produce acetaminophen from resources available in Martian regolith and atmosphere. This proof-of-concept demonstrates the feasibility of creating a biological pharmacy for long-duration missions.',
    keyConcepts: ['Synthetic Biology', 'Pharmaceuticals', 'Mars', 'Yeast Engineering', 'In-Situ Resource Utilization'],
    fullText: 'Details of the engineered metabolic pathway, strain optimization, and a proposed system for scalable production on Mars...',
    doi: '10.1021/acssynbio.3c00456',
  },
  {
    id: 'nasa-bio-011',
    title: 'The Effect of Space Radiation on Plant Genetics and Epigenetics',
    authors: ['Dr. Emily Johnson', 'Dr. Carlos Garcia'],
    publicationDate: '2023-09-21',
    journal: 'The Plant Cell',
    summary: 'This research examines the genetic and epigenetic changes in tomato plants exposed to simulated galactic cosmic radiation (GCR). We found an increased rate of somatic mutations and significant changes in DNA methylation patterns, impacting fruit development.',
    keyConcepts: ['Space Radiation', 'Plant Biology', 'Genetics', 'Epigenetics', 'GCR'],
    fullText: 'Full genome sequencing and bisulfite sequencing data from multiple generations of plants exposed to GCR, correlating epigenetic marks with phenotypic changes...',
    doi: '10.1093/plcell/koad234',
  },
  {
    id: 'nasa-bio-012',
    title: 'Cardiovascular Deconditioning in Space: A Review of Countermeasures',
    authors: ['Dr. Michael Brown', 'Dr. Sophia Loren'],
    publicationDate: '2022-06-10',
    journal: 'Circulation',
    summary: 'This review synthesizes 30 years of research on cardiovascular deconditioning during spaceflight. It evaluates the efficacy of various countermeasures, including exercise, lower body negative pressure, and fluid loading, providing recommendations for future missions.',
    keyConcepts: ['Cardiovascular Health', 'Human Physiology', 'Spaceflight', 'Countermeasures', 'Microgravity'],
    fullText: 'A meta-analysis of studies conducted on Skylab, Mir, the Space Shuttle, and the ISS, providing a comprehensive overview of the physiological changes and the effectiveness of interventions...',
    doi: '10.1161/CIRCULATIONAHA.121.058123',
  },
];
